### ISSUE TITLE
Adding a init system

### ISSUE THREAD

**Issue by KitsuneSemCalda** [RedsonBr140/BlobOS#11]
To initialize this server's background services, add an init system

**Comment by RedsonBr140** [comment]
Well, for now we don't have any plan of creating an init system, as the whole idea of an init system is having a process that spawns other processes.

Also, the init system has to be written as a program for the OS, and not on top of the kernel, take Linux as an example:

![image.png](https://user-images.githubusercontent.com/61910521/224085124-6b02e84f-eeb0-4f54-8147-cc65dddf2ac5.png)

Basically, we plan to write an init system, but we can't do that now.
