### ISSUE TITLE
Fix: Qemu debug from connect into gdb ( // FIXME: For some reason, QEMU won't open port 1234 and GDB will not work.)

### ISSUE THREAD

**Issue by KitsuneSemCalda** [RedsonBr140/BlobOS#25]
I read your debug configuration files in special `.vscode/task.json` and found your problem with qemu

if you check the code in task.json especially this line

```json
 "command": "qemu-system-x86_64 -cdrom build/BlobOS.iso -serial stdio -s -S -boot dc -d int"
```

you can check the lack of the `-gdb` flag to connect to the gnu debugger the correct command is

```json
 "command": "qemu-system-x86_64 -cdrom build/BlobOS.iso -gdb tcp::1234 -serial stdio -s -S -boot dc -d int"
```

with this you can connect qemu to gdb using port 1234

**Comment by RedsonBr140** [comment]
`-s` is already a shorthand for `-gdb tcp::1234`
